<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:decision="http://www.bonitasoft.org/ns/studio/process/decision" xmlns:expression="http://www.bonitasoft.org/ns/studio/expression" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.3/notation" xmlns:process="http://www.bonitasoft.org/ns/studio/process" xsi:schemaLocation="http://www.bonitasoft.org/ns/studio/process/decision http://www.bonitasoft.org/ns/studio/process#//decision">
  <process:MainProcess xmi:id="_iluT4ExDEeyPd6UCU1TUug" name="MyDiagram" author="chris" bonitaVersion="7.13.0" bonitaModelVersion="7.12.0-004">
    <elements xmi:type="process:Pool" xmi:id="_iluT4UxDEeyPd6UCU1TUug" name="Pool">
      <elements xmi:type="process:Lane" xmi:id="_iluT4kxDEeyPd6UCU1TUug" name="Elektriker" actor="_AwsXEFG9EeyQ3LYGAULVzQ">
        <elements xmi:type="process:Task" xmi:id="_iluT50xDEeyPd6UCU1TUug" name="EL Auftrag annehmen" outgoing="_TMSFMFc6EeyZc75ISJff_w" incoming="_9ypOIFc5EeyZc75ISJff_w" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_iluT6ExDEeyPd6UCU1TUug" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_iluT6UxDEeyPd6UCU1TUug" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_iluT6kxDEeyPd6UCU1TUug" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_Kh6p8FzIEey9ZKKEy0NCwA">
            <leftOperand xmi:type="expression:Expression" xmi:id="_Kh6p8VzIEey9ZKKEy0NCwA" name="maschine" content="maschine" type="TYPE_VARIABLE" returnType="com.company.model.Maschine">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_Kh6p8lzIEey9ZKKEy0NCwA" name="maschine" dataType="_iluUFExDEeyPd6UCU1TUug" className="com.company.model.Maschine"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_Kh6p81zIEey9ZKKEy0NCwA" name="maschineInput.nameAntragsteller" content="maschineInput?.nameAntragsteller" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_Kh6p9FzIEey9ZKKEy0NCwA" name="maschineInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_Kh6p9VzIEey9ZKKEy0NCwA" type="JAVA_METHOD" expression="setNameAntragsteller">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_Kh6p9lzIEey9ZKKEy0NCwA">
            <leftOperand xmi:type="expression:Expression" xmi:id="_Kh6p91zIEey9ZKKEy0NCwA" name="maschine" content="maschine" type="TYPE_VARIABLE" returnType="com.company.model.Maschine">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_Kh6p-FzIEey9ZKKEy0NCwA" name="maschine" dataType="_iluUFExDEeyPd6UCU1TUug" className="com.company.model.Maschine"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_Kh6p-VzIEey9ZKKEy0NCwA" name="maschineInput.nameMaschine" content="maschineInput?.nameMaschine" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_Kh6p-lzIEey9ZKKEy0NCwA" name="maschineInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_Kh6p-1zIEey9ZKKEy0NCwA" type="JAVA_METHOD" expression="setNameMaschine">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_Kh6p_FzIEey9ZKKEy0NCwA">
            <leftOperand xmi:type="expression:Expression" xmi:id="_Kh6p_VzIEey9ZKKEy0NCwA" name="maschine" content="maschine" type="TYPE_VARIABLE" returnType="com.company.model.Maschine">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_Kh6p_lzIEey9ZKKEy0NCwA" name="maschine" dataType="_iluUFExDEeyPd6UCU1TUug" className="com.company.model.Maschine"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_Kh6p_1zIEey9ZKKEy0NCwA" name="maschineInput.seriennummer" content="maschineInput?.seriennummer" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_Kh6qAFzIEey9ZKKEy0NCwA" name="maschineInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_Kh6qAVzIEey9ZKKEy0NCwA" type="JAVA_METHOD" expression="setSeriennummer">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_Kh6qAlzIEey9ZKKEy0NCwA">
            <leftOperand xmi:type="expression:Expression" xmi:id="_Kh6qA1zIEey9ZKKEy0NCwA" name="maschine" content="maschine" type="TYPE_VARIABLE" returnType="com.company.model.Maschine">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_Kh6qBFzIEey9ZKKEy0NCwA" name="maschine" dataType="_iluUFExDEeyPd6UCU1TUug" className="com.company.model.Maschine"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_Kh6qBVzIEey9ZKKEy0NCwA" name="maschineInput.hersteller" content="maschineInput?.hersteller" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_Kh6qBlzIEey9ZKKEy0NCwA" name="maschineInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_Kh6qB1zIEey9ZKKEy0NCwA" type="JAVA_METHOD" expression="setHersteller">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_Kh6qCFzIEey9ZKKEy0NCwA">
            <leftOperand xmi:type="expression:Expression" xmi:id="_Kh6qCVzIEey9ZKKEy0NCwA" name="maschine" content="maschine" type="TYPE_VARIABLE" returnType="com.company.model.Maschine">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_Kh6qClzIEey9ZKKEy0NCwA" name="maschine" dataType="_iluUFExDEeyPd6UCU1TUug" className="com.company.model.Maschine"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_Kh6qC1zIEey9ZKKEy0NCwA" name="maschineInput.defekt" content="maschineInput?.defekt" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_Kh6qDFzIEey9ZKKEy0NCwA" name="maschineInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_Kh6qDVzIEey9ZKKEy0NCwA" type="JAVA_METHOD" expression="setDefekt">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_Kh6qDlzIEey9ZKKEy0NCwA">
            <leftOperand xmi:type="expression:Expression" xmi:id="_Kh6qD1zIEey9ZKKEy0NCwA" name="maschine" content="maschine" type="TYPE_VARIABLE" returnType="com.company.model.Maschine">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_Kh6qEFzIEey9ZKKEy0NCwA" name="maschine" dataType="_iluUFExDEeyPd6UCU1TUug" className="com.company.model.Maschine"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_Kh6qEVzIEey9ZKKEy0NCwA" name="maschineInput.beschreibung" content="maschineInput?.beschreibung" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_Kh6qElzIEey9ZKKEy0NCwA" name="maschineInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_Kh6qE1zIEey9ZKKEy0NCwA" type="JAVA_METHOD" expression="setBeschreibung">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_Kh6qFFzIEey9ZKKEy0NCwA">
            <leftOperand xmi:type="expression:Expression" xmi:id="_Kh6qFVzIEey9ZKKEy0NCwA" name="maschine" content="maschine" type="TYPE_VARIABLE" returnType="com.company.model.Maschine">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_Kh6qFlzIEey9ZKKEy0NCwA" name="maschine" dataType="_iluUFExDEeyPd6UCU1TUug" className="com.company.model.Maschine"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_Kh6qF1zIEey9ZKKEy0NCwA" name="maschineInput.ersatzteilBenoetigt" content="maschineInput?.ersatzteilBenoetigt" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_Kh6qGFzIEey9ZKKEy0NCwA" name="maschineInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_Kh6qGVzIEey9ZKKEy0NCwA" type="JAVA_METHOD" expression="setErsatzteilBenoetigt">
              <inputTypes>java.lang.Boolean</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_Kh6qGlzIEey9ZKKEy0NCwA">
            <leftOperand xmi:type="expression:Expression" xmi:id="_Kh6qG1zIEey9ZKKEy0NCwA" name="maschine" content="maschine" type="TYPE_VARIABLE" returnType="com.company.model.Maschine">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_Kh6qHFzIEey9ZKKEy0NCwA" name="maschine" dataType="_iluUFExDEeyPd6UCU1TUug" className="com.company.model.Maschine"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_Kh6qHVzIEey9ZKKEy0NCwA" name="maschineInput.nameReparateur" content="maschineInput?.nameReparateur" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_Kh6qHlzIEey9ZKKEy0NCwA" name="maschineInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_Kh6qH1zIEey9ZKKEy0NCwA" type="JAVA_METHOD" expression="setNameReparateur">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_iluT60xDEeyPd6UCU1TUug" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_iluT7ExDEeyPd6UCU1TUug" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_iluT7UxDEeyPd6UCU1TUug" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_iluT7kxDEeyPd6UCU1TUug" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_iluT70xDEeyPd6UCU1TUug" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_iluT8ExDEeyPd6UCU1TUug">
            <targetForm xmi:type="expression:Expression" xmi:id="_6cxdQFzFEey9ZKKEy0NCwA" name="ELAntragAnnehmen" content="05872613-c1fe-4cea-905d-23953d48be45" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_iluT8kxDEeyPd6UCU1TUug">
            <inputs xmi:type="process:ContractInput" xmi:id="_Kh6C4FzIEey9ZKKEy0NCwA" name="maschineInput" type="COMPLEX" dataReference="maschine" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="_Kh6C4VzIEey9ZKKEy0NCwA" name="nameAntragsteller" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_Kh6C4lzIEey9ZKKEy0NCwA" name="nameMaschine" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_Kh6C41zIEey9ZKKEy0NCwA" name="seriennummer" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_Kh6C5FzIEey9ZKKEy0NCwA" name="hersteller" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_Kh6C5VzIEey9ZKKEy0NCwA" name="defekt" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_Kh6C5lzIEey9ZKKEy0NCwA" name="beschreibung" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_Kh6C51zIEey9ZKKEy0NCwA" name="ersatzteilBenoetigt" type="BOOLEAN" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_Kh6C6FzIEey9ZKKEy0NCwA" name="nameReparateur" createMode="false"/>
            </inputs>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_iluT80xDEeyPd6UCU1TUug" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_SpDcUFc6EeyZc75ISJff_w" name="EL Reparatur möglich?" outgoing="_vNDBQFc6EeyZc75ISJff_w _vl17wFc6EeyZc75ISJff_w" incoming="_TMSFMFc6EeyZc75ISJff_w">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_SpEDYVc6EeyZc75ISJff_w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_SpEDYFc6EeyZc75ISJff_w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_SpEDYlc6EeyZc75ISJff_w" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_exqM4Fc6EeyZc75ISJff_w" name="EL Reparatur durchführen" outgoing="_exgxAFc8EeyZc75ISJff_w" incoming="_vNDBQFc6EeyZc75ISJff_w _gR8ecFc7EeyZc75ISJff_w _GQsjEFc7EeyZc75ISJff_w" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_exqz8Vc6EeyZc75ISJff_w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_exqz8Fc6EeyZc75ISJff_w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_exqz8lc6EeyZc75ISJff_w" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_exqz81c6EeyZc75ISJff_w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_exqz9Fc6EeyZc75ISJff_w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_exqz9Vc6EeyZc75ISJff_w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_exqz91c6EeyZc75ISJff_w" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_exqz9lc6EeyZc75ISJff_w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_exqz-Vc6EeyZc75ISJff_w">
            <targetForm xmi:type="expression:Expression" xmi:id="_sSIuEFzGEey9ZKKEy0NCwA" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_exqz-Fc6EeyZc75ISJff_w"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_exqz-1c6EeyZc75ISJff_w" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_hjk64Fc6EeyZc75ISJff_w" name="EL Ersatzteil bestimmen" outgoing="_1NPpIFc6EeyZc75ISJff_w" incoming="_vl17wFc6EeyZc75ISJff_w _iB-cMFc8EeyZc75ISJff_w" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_hjlh8Vc6EeyZc75ISJff_w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_hjlh8Fc6EeyZc75ISJff_w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_hjlh8lc6EeyZc75ISJff_w" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_hjlh81c6EeyZc75ISJff_w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_hjlh9Fc6EeyZc75ISJff_w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_hjlh9Vc6EeyZc75ISJff_w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_hjlh91c6EeyZc75ISJff_w" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_hjlh9lc6EeyZc75ISJff_w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_hjlh-Vc6EeyZc75ISJff_w">
            <targetForm xmi:type="expression:Expression" xmi:id="_sSIuEVzGEey9ZKKEy0NCwA" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_hjlh-Fc6EeyZc75ISJff_w"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_hjlh-1c6EeyZc75ISJff_w" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_bXuxwFc8EeyZc75ISJff_w" name="EL Reparatur erfolgreich?" outgoing="_iB-cMFc8EeyZc75ISJff_w _jQCKwFc8EeyZc75ISJff_w _nPqpEFc8EeyZc75ISJff_w" incoming="_exgxAFc8EeyZc75ISJff_w">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_bXvY0Vc8EeyZc75ISJff_w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_bXvY0Fc8EeyZc75ISJff_w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_bXvY0lc8EeyZc75ISJff_w" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_k0QWkFc8EeyZc75ISJff_w" name="Keine EL Reparatur mehr möglich" incoming="_nPqpEFc8EeyZc75ISJff_w">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_k0Q9oVc8EeyZc75ISJff_w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_k0Q9oFc8EeyZc75ISJff_w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_k0Q9olc8EeyZc75ISJff_w" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_yxmasExFEeyDI-My2cnkmA" name="Maschinenführer" actor="_BqKVsFG9EeyQ3LYGAULVzQ">
        <elements xmi:type="process:StartEvent" xmi:id="_iluT40xDEeyPd6UCU1TUug" name="Start1" outgoing="_iluT-ExDEeyPd6UCU1TUug">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_iluT5ExDEeyPd6UCU1TUug" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_iluT5UxDEeyPd6UCU1TUug" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_iluT5kxDEeyPd6UCU1TUug" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_9yA8AFc5EeyZc75ISJff_w" name="Fehlertyp1" outgoing="_9ypOIFc5EeyZc75ISJff_w _AEcRoFc6EeyZc75ISJff_w" incoming="_iluT-ExDEeyPd6UCU1TUug _zIDzYFc8EeyZc75ISJff_w">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_9yJe4Vc5EeyZc75ISJff_w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_9yJe4Fc5EeyZc75ISJff_w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_9yJe4lc5EeyZc75ISJff_w" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_CysVsFc8EeyZc75ISJff_w" name="Maschine überprüfen" outgoing="_u15aoFc8EeyZc75ISJff_w" incoming="_DqbO8Fc8EeyZc75ISJff_w _jQCKwFc8EeyZc75ISJff_w" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Cys8wVc8EeyZc75ISJff_w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Cys8wFc8EeyZc75ISJff_w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Cys8wlc8EeyZc75ISJff_w" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_Cys8w1c8EeyZc75ISJff_w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_Cys8xFc8EeyZc75ISJff_w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_Cys8xVc8EeyZc75ISJff_w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_Cys8x1c8EeyZc75ISJff_w" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_Cys8xlc8EeyZc75ISJff_w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_Cys8yVc8EeyZc75ISJff_w">
            <targetForm xmi:type="expression:Expression" xmi:id="_sSIuElzGEey9ZKKEy0NCwA" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_Cys8yFc8EeyZc75ISJff_w"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_Cys8y1c8EeyZc75ISJff_w" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_tHuBkFc8EeyZc75ISJff_w" name="Maschine funktioniert?" outgoing="_zIDzYFc8EeyZc75ISJff_w _4b4dcFc8EeyZc75ISJff_w" incoming="_u15aoFc8EeyZc75ISJff_w">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_tHuBklc8EeyZc75ISJff_w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_tHuBkVc8EeyZc75ISJff_w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_tHuBk1c8EeyZc75ISJff_w" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_35rIQFc8EeyZc75ISJff_w" name="Erfolgreich repariert" incoming="_4b4dcFc8EeyZc75ISJff_w">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_35rvUVc8EeyZc75ISJff_w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_35rvUFc8EeyZc75ISJff_w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_35rvUlc8EeyZc75ISJff_w" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_sN3MMFG8EeyQ3LYGAULVzQ" name="Lager" actor="_88P1EFG8EeyQ3LYGAULVzQ">
        <elements xmi:type="process:XORGateway" xmi:id="_0s244Fc6EeyZc75ISJff_w" name="Ersatzteil vorrätig" outgoing="_-DJ54Fc6EeyZc75ISJff_w _CuRlMFc7EeyZc75ISJff_w" incoming="_1NPpIFc6EeyZc75ISJff_w _eECccFc7EeyZc75ISJff_w">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_0s3f8Vc6EeyZc75ISJff_w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_0s3f8Fc6EeyZc75ISJff_w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_0s3f8lc6EeyZc75ISJff_w" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_AcP4MFc7EeyZc75ISJff_w" name="Ersatzteil bestellen" outgoing="_jDpKAFc7EeyZc75ISJff_w" incoming="_CuRlMFc7EeyZc75ISJff_w" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_AcP4Mlc7EeyZc75ISJff_w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_AcP4MVc7EeyZc75ISJff_w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_AcQfQFc7EeyZc75ISJff_w" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_AcQfQVc7EeyZc75ISJff_w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_AcQfQlc7EeyZc75ISJff_w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_AcQfQ1c7EeyZc75ISJff_w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_AcQfRVc7EeyZc75ISJff_w" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_AcQfRFc7EeyZc75ISJff_w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_AcQfR1c7EeyZc75ISJff_w">
            <targetForm xmi:type="expression:Expression" xmi:id="_sSIuE1zGEey9ZKKEy0NCwA" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_AcQfRlc7EeyZc75ISJff_w"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_AcQfSVc7EeyZc75ISJff_w" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_gR2-4Fc7EeyZc75ISJff_w" name="Fehlertyp2" outgoing="_gR8ecFc7EeyZc75ISJff_w _h0-XcFc7EeyZc75ISJff_w" incoming="_-DJ54Fc6EeyZc75ISJff_w">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_gR3l8Vc7EeyZc75ISJff_w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_gR3l8Fc7EeyZc75ISJff_w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_gR3l8lc7EeyZc75ISJff_w" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_iuDUgFc7EeyZc75ISJff_w" name="Fehlertyp3" outgoing="_GQsjEFc7EeyZc75ISJff_w _lRCOoFc7EeyZc75ISJff_w" incoming="_jDpKAFc7EeyZc75ISJff_w">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_iuD7kVc7EeyZc75ISJff_w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_iuD7kFc7EeyZc75ISJff_w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_iuD7klc7EeyZc75ISJff_w" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_zAo8QExFEeyDI-My2cnkmA" name="Mechatroniker" actor="__ZhIwFG8EeyQ3LYGAULVzQ">
        <elements xmi:type="process:Task" xmi:id="__nw8sFc5EeyZc75ISJff_w" name="ME Auftrag annehmen" outgoing="_Qyft4Fc7EeyZc75ISJff_w" incoming="_AEcRoFc6EeyZc75ISJff_w" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="__nw8slc5EeyZc75ISJff_w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="__nw8sVc5EeyZc75ISJff_w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="__nw8s1c5EeyZc75ISJff_w" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="__nw8tFc5EeyZc75ISJff_w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="__nw8tVc5EeyZc75ISJff_w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="__nw8tlc5EeyZc75ISJff_w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="__nxjwFc5EeyZc75ISJff_w" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="__nw8t1c5EeyZc75ISJff_w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="__nxjwlc5EeyZc75ISJff_w">
            <targetForm xmi:type="expression:Expression" xmi:id="_sSIuFFzGEey9ZKKEy0NCwA" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="__nxjwVc5EeyZc75ISJff_w"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="__nxjxFc5EeyZc75ISJff_w" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_QU0TYFc7EeyZc75ISJff_w" name="ME Reparatur möglich?" outgoing="_byhs0Fc7EeyZc75ISJff_w _cQHAsFc7EeyZc75ISJff_w" incoming="_Qyft4Fc7EeyZc75ISJff_w">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_QU06cVc7EeyZc75ISJff_w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_QU06cFc7EeyZc75ISJff_w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_QU06clc7EeyZc75ISJff_w" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_TFkjwFc7EeyZc75ISJff_w" name="ME Reparatur durchführen" outgoing="_6tgXQFc7EeyZc75ISJff_w" incoming="_cQHAsFc7EeyZc75ISJff_w _h0-XcFc7EeyZc75ISJff_w _lRCOoFc7EeyZc75ISJff_w" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_TFlK0Vc7EeyZc75ISJff_w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_TFlK0Fc7EeyZc75ISJff_w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_TFlK0lc7EeyZc75ISJff_w" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_TFlK01c7EeyZc75ISJff_w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_TFlK1Fc7EeyZc75ISJff_w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_TFlK1Vc7EeyZc75ISJff_w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_TFlK11c7EeyZc75ISJff_w" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_TFlK1lc7EeyZc75ISJff_w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_TFlK2Vc7EeyZc75ISJff_w">
            <targetForm xmi:type="expression:Expression" xmi:id="_sSIuFVzGEey9ZKKEy0NCwA" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_TFlK2Fc7EeyZc75ISJff_w"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_TFlK21c7EeyZc75ISJff_w" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_aHd5MFc7EeyZc75ISJff_w" name="ME Ersatzteil bestimmen" outgoing="_eECccFc7EeyZc75ISJff_w" incoming="_byhs0Fc7EeyZc75ISJff_w _7KGzsFc7EeyZc75ISJff_w" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_aHegQVc7EeyZc75ISJff_w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_aHegQFc7EeyZc75ISJff_w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_aHegQlc7EeyZc75ISJff_w" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_aHegQ1c7EeyZc75ISJff_w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_aHegRFc7EeyZc75ISJff_w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_aHegRVc7EeyZc75ISJff_w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_aHegR1c7EeyZc75ISJff_w" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_aHegRlc7EeyZc75ISJff_w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_aHegSVc7EeyZc75ISJff_w">
            <targetForm xmi:type="expression:Expression" xmi:id="_sSIuFlzGEey9ZKKEy0NCwA" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_aHegSFc7EeyZc75ISJff_w"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_aHegS1c7EeyZc75ISJff_w" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_6I_U8Fc7EeyZc75ISJff_w" name="ME Reparatur erfolgreich?" outgoing="_7KGzsFc7EeyZc75ISJff_w _DqbO8Fc8EeyZc75ISJff_w _Y7958Fc8EeyZc75ISJff_w" incoming="_6tgXQFc7EeyZc75ISJff_w">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_6I_8AVc7EeyZc75ISJff_w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_6I_8AFc7EeyZc75ISJff_w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_6I_8Alc7EeyZc75ISJff_w" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_UzCVsFc8EeyZc75ISJff_w" name="Keine ME Reparatur mehr möglich" incoming="_Y7958Fc8EeyZc75ISJff_w">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_UzC8wVc8EeyZc75ISJff_w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_UzC8wFc8EeyZc75ISJff_w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_UzC8wlc8EeyZc75ISJff_w" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <data xmi:type="process:BusinessObjectData" xmi:id="_F6WbMFzDEey9ZKKEy0NCwA" name="maschine" dataType="_iluUFExDEeyPd6UCU1TUug" className="com.company.model.Maschine">
        <defaultValue xmi:type="expression:Expression" xmi:id="_KUXIZ1zDEey9ZKKEy0NCwA" name="initMaschine()" content="def maschineVar = new com.company.model.Maschine()&#xD;&#xA;maschineVar.nameAntragsteller = maschineInput?.nameAntragsteller&#xD;&#xA;maschineVar.nameMaschine = maschineInput?.nameMaschine&#xD;&#xA;maschineVar.seriennummer = maschineInput?.seriennummer&#xD;&#xA;maschineVar.hersteller = maschineInput?.hersteller&#xD;&#xA;maschineVar.defekt = maschineInput?.defekt&#xD;&#xA;maschineVar.beschreibung = maschineInput?.beschreibung&#xD;&#xA;return maschineVar" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="com.company.model.Maschine">
          <referencedElements xmi:type="process:ContractInput" xmi:id="_KUXIaFzDEey9ZKKEy0NCwA" name="maschineInput" type="COMPLEX"/>
        </defaultValue>
      </data>
      <formMapping xmi:type="process:FormMapping" xmi:id="_iluT9ExDEeyPd6UCU1TUug">
        <targetForm xmi:type="expression:Expression" xmi:id="_9MfTcFdBEeyZc75ISJff_w" name="defektMelden" content="8978a360-4c3a-4bef-a11f-0002432544a8" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_iluT9kxDEeyPd6UCU1TUug">
        <targetForm xmi:type="expression:Expression" xmi:id="_iluT90xDEeyPd6UCU1TUug" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_iluT-ExDEeyPd6UCU1TUug" target="_9yA8AFc5EeyZc75ISJff_w" source="_iluT40xDEeyPd6UCU1TUug">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_iluT-UxDEeyPd6UCU1TUug"/>
        <condition xmi:type="expression:Expression" xmi:id="_iluT-kxDEeyPd6UCU1TUug" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_9ypOIFc5EeyZc75ISJff_w" name="elektrischerDefekt" target="_iluT50xDEeyPd6UCU1TUug" source="_9yA8AFc5EeyZc75ISJff_w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_9yp1MFc5EeyZc75ISJff_w"/>
        <condition xmi:type="expression:Expression" xmi:id="_9yp1MVc5EeyZc75ISJff_w" name="newScript()" content="maschine.defekt == &quot;Elektrisch&quot;" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_O9a-MFzDEey9ZKKEy0NCwA" name="maschine" dataType="_iluUFExDEeyPd6UCU1TUug" className="com.company.model.Maschine"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_AEcRoFc6EeyZc75ISJff_w" name="mechanischer Defekt" target="__nw8sFc5EeyZc75ISJff_w" source="_9yA8AFc5EeyZc75ISJff_w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_AEc4sFc6EeyZc75ISJff_w"/>
        <condition xmi:type="expression:Expression" xmi:id="_AEc4sVc6EeyZc75ISJff_w" name="newScript()" content="maschine.defekt == &quot;Mechanisch&quot;" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_ROJqsFzDEey9ZKKEy0NCwA" name="maschine" dataType="_iluUFExDEeyPd6UCU1TUug" className="com.company.model.Maschine"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_TMSFMFc6EeyZc75ISJff_w" target="_SpDcUFc6EeyZc75ISJff_w" source="_iluT50xDEeyPd6UCU1TUug">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_TMSsQFc6EeyZc75ISJff_w"/>
        <condition xmi:type="expression:Expression" xmi:id="_TMSsQVc6EeyZc75ISJff_w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_vNDBQFc6EeyZc75ISJff_w" target="_exqM4Fc6EeyZc75ISJff_w" source="_SpDcUFc6EeyZc75ISJff_w" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_vNDBQVc6EeyZc75ISJff_w"/>
        <condition xmi:type="expression:Expression" xmi:id="_vNDBQlc6EeyZc75ISJff_w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_vl17wFc6EeyZc75ISJff_w" target="_hjk64Fc6EeyZc75ISJff_w" source="_SpDcUFc6EeyZc75ISJff_w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_vl17wVc6EeyZc75ISJff_w"/>
        <condition xmi:type="expression:Expression" xmi:id="_vl17wlc6EeyZc75ISJff_w" name="newScript()" content="maschine.ersatzteilBenoetigt" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_ie72AFzDEey9ZKKEy0NCwA" name="maschine" dataType="_iluUFExDEeyPd6UCU1TUug" className="com.company.model.Maschine"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_1NPpIFc6EeyZc75ISJff_w" target="_0s244Fc6EeyZc75ISJff_w" source="_hjk64Fc6EeyZc75ISJff_w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_1NPpIVc6EeyZc75ISJff_w"/>
        <condition xmi:type="expression:Expression" xmi:id="_1NQQMFc6EeyZc75ISJff_w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_-DJ54Fc6EeyZc75ISJff_w" target="_gR2-4Fc7EeyZc75ISJff_w" source="_0s244Fc6EeyZc75ISJff_w" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_-DJ54Vc6EeyZc75ISJff_w"/>
        <condition xmi:type="expression:Expression" xmi:id="_-DJ54lc6EeyZc75ISJff_w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_CuRlMFc7EeyZc75ISJff_w" target="_AcP4MFc7EeyZc75ISJff_w" source="_0s244Fc6EeyZc75ISJff_w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_CuSMQFc7EeyZc75ISJff_w"/>
        <condition xmi:type="expression:Expression" xmi:id="_CuSMQVc7EeyZc75ISJff_w" name="newScript()" content="!maschine.ersatzteilVorraetig" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_qojogFzDEey9ZKKEy0NCwA" name="maschine" dataType="_iluUFExDEeyPd6UCU1TUug" className="com.company.model.Maschine"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_GQsjEFc7EeyZc75ISJff_w" target="_exqM4Fc6EeyZc75ISJff_w" source="_iuDUgFc7EeyZc75ISJff_w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_GQsjEVc7EeyZc75ISJff_w"/>
        <condition xmi:type="expression:Expression" xmi:id="_GQtKIFc7EeyZc75ISJff_w" name="newScript()" content="maschine.defekt == &quot;Elektrisch&quot;" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_ZsK_4FzDEey9ZKKEy0NCwA" name="maschine" dataType="_iluUFExDEeyPd6UCU1TUug" className="com.company.model.Maschine"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Qyft4Fc7EeyZc75ISJff_w" target="_QU0TYFc7EeyZc75ISJff_w" source="__nw8sFc5EeyZc75ISJff_w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Qyft4Vc7EeyZc75ISJff_w"/>
        <condition xmi:type="expression:Expression" xmi:id="_Qyft4lc7EeyZc75ISJff_w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_byhs0Fc7EeyZc75ISJff_w" target="_aHd5MFc7EeyZc75ISJff_w" source="_QU0TYFc7EeyZc75ISJff_w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_byhs0Vc7EeyZc75ISJff_w"/>
        <condition xmi:type="expression:Expression" xmi:id="_byhs0lc7EeyZc75ISJff_w" name="newScript()" content="maschine.ersatzteilBenoetigt" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_wNiUAFzDEey9ZKKEy0NCwA" name="maschine" dataType="_iluUFExDEeyPd6UCU1TUug" className="com.company.model.Maschine"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_cQHAsFc7EeyZc75ISJff_w" target="_TFkjwFc7EeyZc75ISJff_w" source="_QU0TYFc7EeyZc75ISJff_w" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_cQHAsVc7EeyZc75ISJff_w"/>
        <condition xmi:type="expression:Expression" xmi:id="_cQHnwFc7EeyZc75ISJff_w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_eECccFc7EeyZc75ISJff_w" target="_0s244Fc6EeyZc75ISJff_w" source="_aHd5MFc7EeyZc75ISJff_w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_eEDDgFc7EeyZc75ISJff_w"/>
        <condition xmi:type="expression:Expression" xmi:id="_eEDDgVc7EeyZc75ISJff_w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_gR8ecFc7EeyZc75ISJff_w" target="_exqM4Fc6EeyZc75ISJff_w" source="_gR2-4Fc7EeyZc75ISJff_w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_gR8ecVc7EeyZc75ISJff_w"/>
        <condition xmi:type="expression:Expression" xmi:id="_gR9FgFc7EeyZc75ISJff_w" name="newScript()" content="maschine.defekt == &quot;Elektrisch&quot;" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_UQvR8FzDEey9ZKKEy0NCwA" name="maschine" dataType="_iluUFExDEeyPd6UCU1TUug" className="com.company.model.Maschine"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_h0-XcFc7EeyZc75ISJff_w" target="_TFkjwFc7EeyZc75ISJff_w" source="_gR2-4Fc7EeyZc75ISJff_w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_h0-XcVc7EeyZc75ISJff_w"/>
        <condition xmi:type="expression:Expression" xmi:id="_h0-Xclc7EeyZc75ISJff_w" name="newScript()" content="maschine.defekt == &quot;Mechanisch&quot;" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_WeF6UFzDEey9ZKKEy0NCwA" name="maschine" dataType="_iluUFExDEeyPd6UCU1TUug" className="com.company.model.Maschine"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_jDpKAFc7EeyZc75ISJff_w" target="_iuDUgFc7EeyZc75ISJff_w" source="_AcP4MFc7EeyZc75ISJff_w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_jDpxEFc7EeyZc75ISJff_w"/>
        <condition xmi:type="expression:Expression" xmi:id="_jDpxEVc7EeyZc75ISJff_w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_lRCOoFc7EeyZc75ISJff_w" target="_TFkjwFc7EeyZc75ISJff_w" source="_iuDUgFc7EeyZc75ISJff_w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_lRCOoVc7EeyZc75ISJff_w"/>
        <condition xmi:type="expression:Expression" xmi:id="_lRC1sFc7EeyZc75ISJff_w" name="newScript()" content="maschine.defekt == &quot;Mechanisch&quot;" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_b7pIIFzDEey9ZKKEy0NCwA" name="maschine" dataType="_iluUFExDEeyPd6UCU1TUug" className="com.company.model.Maschine"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_6tgXQFc7EeyZc75ISJff_w" target="_6I_U8Fc7EeyZc75ISJff_w" source="_TFkjwFc7EeyZc75ISJff_w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_6tgXQVc7EeyZc75ISJff_w"/>
        <condition xmi:type="expression:Expression" xmi:id="_6tgXQlc7EeyZc75ISJff_w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_7KGzsFc7EeyZc75ISJff_w" target="_aHd5MFc7EeyZc75ISJff_w" source="_6I_U8Fc7EeyZc75ISJff_w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_7KHawFc7EeyZc75ISJff_w"/>
        <condition xmi:type="expression:Expression" xmi:id="_7KHawVc7EeyZc75ISJff_w" name="newScript()" content="maschine.status == &quot;TeilBenoetigt&quot;" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_xetoAFzDEey9ZKKEy0NCwA" name="maschine" dataType="_iluUFExDEeyPd6UCU1TUug" className="com.company.model.Maschine"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_DqbO8Fc8EeyZc75ISJff_w" target="_CysVsFc8EeyZc75ISJff_w" source="_6I_U8Fc7EeyZc75ISJff_w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_DqbO8Vc8EeyZc75ISJff_w"/>
        <condition xmi:type="expression:Expression" xmi:id="_DqbO8lc8EeyZc75ISJff_w" name="newScript()" content="maschine.status == &quot;Erfolgreich&quot;" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_r9NuUFzDEey9ZKKEy0NCwA" name="maschine" dataType="_iluUFExDEeyPd6UCU1TUug" className="com.company.model.Maschine"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Y7958Fc8EeyZc75ISJff_w" target="_UzCVsFc8EeyZc75ISJff_w" source="_6I_U8Fc7EeyZc75ISJff_w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Y7958Vc8EeyZc75ISJff_w"/>
        <condition xmi:type="expression:Expression" xmi:id="_Y7958lc8EeyZc75ISJff_w" name="newScript()" content="maschine.status == &quot;Totalschaden&quot;" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_tKzi0FzDEey9ZKKEy0NCwA" name="maschine" dataType="_iluUFExDEeyPd6UCU1TUug" className="com.company.model.Maschine"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_exgxAFc8EeyZc75ISJff_w" target="_bXuxwFc8EeyZc75ISJff_w" source="_exqM4Fc6EeyZc75ISJff_w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_exhYEFc8EeyZc75ISJff_w"/>
        <condition xmi:type="expression:Expression" xmi:id="_exhYEVc8EeyZc75ISJff_w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_iB-cMFc8EeyZc75ISJff_w" target="_hjk64Fc6EeyZc75ISJff_w" source="_bXuxwFc8EeyZc75ISJff_w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_iB-cMVc8EeyZc75ISJff_w"/>
        <condition xmi:type="expression:Expression" xmi:id="_iB-cMlc8EeyZc75ISJff_w" name="newScript()" content="maschine.status.equalsIgnoreCase(&quot;TeilBenoetigt&quot;)" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_ka3-QFzDEey9ZKKEy0NCwA" name="maschine" dataType="_iluUFExDEeyPd6UCU1TUug" className="com.company.model.Maschine"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_jQCKwFc8EeyZc75ISJff_w" target="_CysVsFc8EeyZc75ISJff_w" source="_bXuxwFc8EeyZc75ISJff_w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_jQCKwVc8EeyZc75ISJff_w"/>
        <condition xmi:type="expression:Expression" xmi:id="_jQCKwlc8EeyZc75ISJff_w" name="newScript()" content="maschine.status.equalsIgnoreCase(&quot;Erfolgreich&quot;)" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_oSr9UFzDEey9ZKKEy0NCwA" name="maschine" dataType="_iluUFExDEeyPd6UCU1TUug" className="com.company.model.Maschine"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_nPqpEFc8EeyZc75ISJff_w" target="_k0QWkFc8EeyZc75ISJff_w" source="_bXuxwFc8EeyZc75ISJff_w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_nPqpEVc8EeyZc75ISJff_w"/>
        <condition xmi:type="expression:Expression" xmi:id="_nPqpElc8EeyZc75ISJff_w" name="newScript()" content="maschine.status == &quot;Totalschaden&quot;" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_m9QbcFzDEey9ZKKEy0NCwA" name="maschine" dataType="_iluUFExDEeyPd6UCU1TUug" className="com.company.model.Maschine"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_u15aoFc8EeyZc75ISJff_w" target="_tHuBkFc8EeyZc75ISJff_w" source="_CysVsFc8EeyZc75ISJff_w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_u15aoVc8EeyZc75ISJff_w"/>
        <condition xmi:type="expression:Expression" xmi:id="_u15aolc8EeyZc75ISJff_w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_zIDzYFc8EeyZc75ISJff_w" target="_9yA8AFc5EeyZc75ISJff_w" source="_tHuBkFc8EeyZc75ISJff_w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_zIDzYVc8EeyZc75ISJff_w"/>
        <condition xmi:type="expression:Expression" xmi:id="_zIEacFc8EeyZc75ISJff_w" name="newScript()" content="maschine.status == &quot;UeberarbeitungNoetig&quot;" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_fNtV0FzDEey9ZKKEy0NCwA" name="maschine" dataType="_iluUFExDEeyPd6UCU1TUug" className="com.company.model.Maschine"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_4b4dcFc8EeyZc75ISJff_w" target="_35rIQFc8EeyZc75ISJff_w" source="_tHuBkFc8EeyZc75ISJff_w" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_4b4dcVc8EeyZc75ISJff_w"/>
        <condition xmi:type="expression:Expression" xmi:id="_4b4dclc8EeyZc75ISJff_w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_88P1EFG8EeyQ3LYGAULVzQ" name="Lagerist"/>
      <actors xmi:type="process:Actor" xmi:id="__ZhIwFG8EeyQ3LYGAULVzQ" name="Mechatroniker"/>
      <actors xmi:type="process:Actor" xmi:id="_AwsXEFG9EeyQ3LYGAULVzQ" name="Elektriker"/>
      <actors xmi:type="process:Actor" xmi:id="_BqKVsFG9EeyQ3LYGAULVzQ" name="Maschinenführer" initiator="true"/>
      <contract xmi:type="process:Contract" xmi:id="_iluT_ExDEeyPd6UCU1TUug">
        <inputs xmi:type="process:ContractInput" xmi:id="_KUXIYFzDEey9ZKKEy0NCwA" name="maschineInput" type="COMPLEX" dataReference="maschine">
          <inputs xmi:type="process:ContractInput" xmi:id="_KUXIYVzDEey9ZKKEy0NCwA" name="nameAntragsteller"/>
          <inputs xmi:type="process:ContractInput" xmi:id="_KUXIYlzDEey9ZKKEy0NCwA" name="nameMaschine"/>
          <inputs xmi:type="process:ContractInput" xmi:id="_KUXIY1zDEey9ZKKEy0NCwA" name="seriennummer"/>
          <inputs xmi:type="process:ContractInput" xmi:id="_KUXIZFzDEey9ZKKEy0NCwA" name="hersteller"/>
          <inputs xmi:type="process:ContractInput" xmi:id="_KUXIZVzDEey9ZKKEy0NCwA" name="defekt"/>
          <inputs xmi:type="process:ContractInput" xmi:id="_KUXIZlzDEey9ZKKEy0NCwA" name="beschreibung"/>
        </inputs>
      </contract>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_iluT_UxDEeyPd6UCU1TUug">
        <name xmi:type="expression:Expression" xmi:id="_iluT_kxDEeyPd6UCU1TUug" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_iluT_0xDEeyPd6UCU1TUug" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_iluUAExDEeyPd6UCU1TUug">
        <name xmi:type="expression:Expression" xmi:id="_iluUAUxDEeyPd6UCU1TUug" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_iluUAkxDEeyPd6UCU1TUug" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_iluUA0xDEeyPd6UCU1TUug">
        <name xmi:type="expression:Expression" xmi:id="_iluUBExDEeyPd6UCU1TUug" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_iluUBUxDEeyPd6UCU1TUug" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_iluUBkxDEeyPd6UCU1TUug">
        <name xmi:type="expression:Expression" xmi:id="_iluUB0xDEeyPd6UCU1TUug" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_iluUCExDEeyPd6UCU1TUug" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_iluUCUxDEeyPd6UCU1TUug">
        <name xmi:type="expression:Expression" xmi:id="_iluUCkxDEeyPd6UCU1TUug" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_iluUC0xDEeyPd6UCU1TUug" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <datatypes xmi:type="process:BooleanType" xmi:id="_iluUDExDEeyPd6UCU1TUug" name="Boolean"/>
    <datatypes xmi:type="process:DateType" xmi:id="_iluUDUxDEeyPd6UCU1TUug" name="Date"/>
    <datatypes xmi:type="process:IntegerType" xmi:id="_iluUDkxDEeyPd6UCU1TUug" name="Integer"/>
    <datatypes xmi:type="process:LongType" xmi:id="_iluUD0xDEeyPd6UCU1TUug" name="Long"/>
    <datatypes xmi:type="process:DoubleType" xmi:id="_iluUEExDEeyPd6UCU1TUug" name="Double"/>
    <datatypes xmi:type="process:StringType" xmi:id="_iluUEUxDEeyPd6UCU1TUug" name="Text"/>
    <datatypes xmi:type="process:JavaType" xmi:id="_iluUEkxDEeyPd6UCU1TUug" name="Java_object"/>
    <datatypes xmi:type="process:XMLType" xmi:id="_iluUE0xDEeyPd6UCU1TUug" name="XML"/>
    <datatypes xmi:type="process:BusinessObjectType" xmi:id="_iluUFExDEeyPd6UCU1TUug" name="Business_Object"/>
    <datatypes xmi:type="process:EnumType" xmi:id="_DmYqcFHAEeyQ3LYGAULVzQ" name="defektTyp">
      <literals>elektrisch</literals>
      <literals>mechanisch</literals>
    </datatypes>
  </process:MainProcess>
  <notation:Diagram xmi:id="_iluUFUxDEeyPd6UCU1TUug" type="Process" element="_iluT4ExDEeyPd6UCU1TUug" name="MyDiagram" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_iluUFkxDEeyPd6UCU1TUug" type="2007" element="_iluT4UxDEeyPd6UCU1TUug">
      <children xmi:type="notation:DecorationNode" xmi:id="_iluUF0xDEeyPd6UCU1TUug" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_iluUGExDEeyPd6UCU1TUug" type="7001">
        <children xmi:type="notation:Node" xmi:id="_iluUGUxDEeyPd6UCU1TUug" type="3007" element="_iluT4kxDEeyPd6UCU1TUug">
          <children xmi:type="notation:DecorationNode" xmi:id="_iluUGkxDEeyPd6UCU1TUug" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_iluUG0xDEeyPd6UCU1TUug" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_iluUHExDEeyPd6UCU1TUug" type="3005" element="_iluT50xDEeyPd6UCU1TUug" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_iluUHUxDEeyPd6UCU1TUug" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_iluUHkxDEeyPd6UCU1TUug" x="168" y="84"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_SpEqcFc6EeyZc75ISJff_w" type="3008" element="_SpDcUFc6EeyZc75ISJff_w" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_SpEqclc6EeyZc75ISJff_w" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_SpEqc1c6EeyZc75ISJff_w" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_SpEqcVc6EeyZc75ISJff_w" x="346" y="90"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_exrbAFc6EeyZc75ISJff_w" type="3005" element="_exqM4Fc6EeyZc75ISJff_w" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_exsCEFc6EeyZc75ISJff_w" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_exrbAVc6EeyZc75ISJff_w" x="764" y="90" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_hjnXIFc6EeyZc75ISJff_w" type="3005" element="_hjk64Fc6EeyZc75ISJff_w" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_hjnXIlc6EeyZc75ISJff_w" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_hjnXIVc6EeyZc75ISJff_w" x="517" y="149" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_bXv_4Fc8EeyZc75ISJff_w" type="3008" element="_bXuxwFc8EeyZc75ISJff_w" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_bXv_4lc8EeyZc75ISJff_w" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_bXwm8Fc8EeyZc75ISJff_w" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_bXv_4Vc8EeyZc75ISJff_w" x="992" y="98"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_k0RksFc8EeyZc75ISJff_w" type="3003" element="_k0QWkFc8EeyZc75ISJff_w" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_k0Rkslc8EeyZc75ISJff_w" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_k0Rks1c8EeyZc75ISJff_w" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_k0RksVc8EeyZc75ISJff_w" x="999" y="198"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_iluUI0xDEeyPd6UCU1TUug"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_iluUJExDEeyPd6UCU1TUug" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_iluUJUxDEeyPd6UCU1TUug"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_iluUJkxDEeyPd6UCU1TUug"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_iluUJ0xDEeyPd6UCU1TUug" x="23" y="10" width="2257" height="269"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_yxqFEExFEeyDI-My2cnkmA" type="3007" element="_yxmasExFEeyDI-My2cnkmA">
          <children xmi:type="notation:DecorationNode" xmi:id="_yxqsIExFEeyDI-My2cnkmA" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_yxqsIUxFEeyDI-My2cnkmA" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_iluUH0xDEeyPd6UCU1TUug" type="3002" element="_iluT40xDEeyPd6UCU1TUug" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_iluUIExDEeyPd6UCU1TUug" type="5024">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_iluUIUxDEeyPd6UCU1TUug" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_iluUIkxDEeyPd6UCU1TUug" x="77" y="70"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_9yTP4Fc5EeyZc75ISJff_w" type="3008" element="_9yA8AFc5EeyZc75ISJff_w" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_9yT28Fc5EeyZc75ISJff_w" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_9yT28Vc5EeyZc75ISJff_w" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_9yTP4Vc5EeyZc75ISJff_w" x="196" y="59"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Cytj0Fc8EeyZc75ISJff_w" type="3005" element="_CysVsFc8EeyZc75ISJff_w" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_CyuK4Fc8EeyZc75ISJff_w" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Cytj0Vc8EeyZc75ISJff_w" x="1220" y="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_tHuooFc8EeyZc75ISJff_w" type="3008" element="_tHuBkFc8EeyZc75ISJff_w" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_tHuoolc8EeyZc75ISJff_w" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_tHuoo1c8EeyZc75ISJff_w" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_tHuooVc8EeyZc75ISJff_w" x="1410" y="64"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_35s9cFc8EeyZc75ISJff_w" type="3003" element="_35rIQFc8EeyZc75ISJff_w" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_35s9clc8EeyZc75ISJff_w" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_35s9c1c8EeyZc75ISJff_w" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_35s9cVc8EeyZc75ISJff_w" x="1581" y="70"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_yxqFEUxFEeyDI-My2cnkmA"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_yxqFEkxFEeyDI-My2cnkmA" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_yxqFE0xFEeyDI-My2cnkmA"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_yxqsIkxFEeyDI-My2cnkmA"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_yxqFFExFEeyDI-My2cnkmA" x="23" y="180" width="2257" height="171"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_zAqKYExFEeyDI-My2cnkmA" type="3007" element="_zAo8QExFEeyDI-My2cnkmA">
          <children xmi:type="notation:DecorationNode" xmi:id="_zAqKZUxFEeyDI-My2cnkmA" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_zAqKZkxFEeyDI-My2cnkmA" type="7002">
            <children xmi:type="notation:Shape" xmi:id="__n1OIFc5EeyZc75ISJff_w" type="3005" element="__nw8sFc5EeyZc75ISJff_w" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="__n1OIlc5EeyZc75ISJff_w" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="__n1OIVc5EeyZc75ISJff_w" x="168" y="75"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_QU1hgFc7EeyZc75ISJff_w" type="3008" element="_QU0TYFc7EeyZc75ISJff_w" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_QU1hglc7EeyZc75ISJff_w" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_QU1hg1c7EeyZc75ISJff_w" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_QU1hgVc7EeyZc75ISJff_w" x="403" y="78"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_TFlx4Fc7EeyZc75ISJff_w" type="3005" element="_TFkjwFc7EeyZc75ISJff_w" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_TFlx4lc7EeyZc75ISJff_w" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_TFlx4Vc7EeyZc75ISJff_w" x="783" y="78" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_aHfHUFc7EeyZc75ISJff_w" type="3005" element="_aHd5MFc7EeyZc75ISJff_w" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_aHfuYFc7EeyZc75ISJff_w" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_aHfHUVc7EeyZc75ISJff_w" x="517" y="13" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_6JAjEFc7EeyZc75ISJff_w" type="3008" element="_6I_U8Fc7EeyZc75ISJff_w" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_6JBKIFc7EeyZc75ISJff_w" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_6JBKIVc7EeyZc75ISJff_w" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_6JAjEVc7EeyZc75ISJff_w" x="1028" y="93"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_UzDj0Fc8EeyZc75ISJff_w" type="3003" element="_UzCVsFc8EeyZc75ISJff_w" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_UzDj0lc8EeyZc75ISJff_w" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_UzDj01c8EeyZc75ISJff_w" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_UzDj0Vc8EeyZc75ISJff_w" x="1182" y="49"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_zAqKYUxFEeyDI-My2cnkmA"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_zAqKYkxFEeyDI-My2cnkmA" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_zAqKY0xFEeyDI-My2cnkmA"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_zAqKZ0xFEeyDI-My2cnkmA"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_zAqKZExFEeyDI-My2cnkmA" x="23" y="679" width="2257" height="230"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_sN3zQFG8EeyQ3LYGAULVzQ" type="3007" element="_sN3MMFG8EeyQ3LYGAULVzQ">
          <children xmi:type="notation:DecorationNode" xmi:id="_sN3zRVG8EeyQ3LYGAULVzQ" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_sN3zRlG8EeyQ3LYGAULVzQ" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_0s4HAFc6EeyZc75ISJff_w" type="3008" element="_0s244Fc6EeyZc75ISJff_w" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_0s4HAlc6EeyZc75ISJff_w" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_0s4HA1c6EeyZc75ISJff_w" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_0s4HAVc6EeyZc75ISJff_w" x="555" y="103"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_AcRGUFc7EeyZc75ISJff_w" type="3005" element="_AcP4MFc7EeyZc75ISJff_w" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_AcRGUlc7EeyZc75ISJff_w" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_AcRGUVc7EeyZc75ISJff_w" x="897" y="95" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_gR4NAFc7EeyZc75ISJff_w" type="3008" element="_gR2-4Fc7EeyZc75ISJff_w" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_gR4NAlc7EeyZc75ISJff_w" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_gR4NA1c7EeyZc75ISJff_w" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_gR4NAVc7EeyZc75ISJff_w" x="783" y="43"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_iuEioFc7EeyZc75ISJff_w" type="3008" element="_iuDUgFc7EeyZc75ISJff_w" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_iuEiolc7EeyZc75ISJff_w" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_iuEio1c7EeyZc75ISJff_w" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_iuEioVc7EeyZc75ISJff_w" x="1106" y="103"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_sN3zQVG8EeyQ3LYGAULVzQ"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_sN3zQlG8EeyQ3LYGAULVzQ" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_sN3zQ1G8EeyQ3LYGAULVzQ"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_sN4aUFG8EeyQ3LYGAULVzQ"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_sN3zRFG8EeyQ3LYGAULVzQ" x="23" y="565" width="2257" height="285"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_iluUKExDEeyPd6UCU1TUug"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_iluUKUxDEeyPd6UCU1TUug" fontName="Segoe UI"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_iluUKkxDEeyPd6UCU1TUug"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_iluUK0xDEeyPd6UCU1TUug"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_iluULExDEeyPd6UCU1TUug" width="2280" height="250"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_iluULUxDEeyPd6UCU1TUug"/>
    <edges xmi:type="notation:Connector" xmi:id="_iluULkxDEeyPd6UCU1TUug" type="4001" element="_iluT-ExDEeyPd6UCU1TUug" source="_iluUH0xDEeyPd6UCU1TUug" target="_9yTP4Fc5EeyZc75ISJff_w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_iluUL0xDEeyPd6UCU1TUug" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_iluUMExDEeyPd6UCU1TUug" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_iluUMUxDEeyPd6UCU1TUug" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_iluUMkxDEeyPd6UCU1TUug" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_9ysRcFc5EeyZc75ISJff_w" type="4001" element="_9ypOIFc5EeyZc75ISJff_w" source="_9yTP4Fc5EeyZc75ISJff_w" target="_iluUHExDEeyPd6UCU1TUug" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_9ysRc1c5EeyZc75ISJff_w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_9ysRdFc5EeyZc75ISJff_w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_9ysRcVc5EeyZc75ISJff_w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_9ysRclc5EeyZc75ISJff_w" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_AEmpsFc6EeyZc75ISJff_w" type="4001" element="_AEcRoFc6EeyZc75ISJff_w" source="_9yTP4Fc5EeyZc75ISJff_w" target="__n1OIFc5EeyZc75ISJff_w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_AEnQwFc6EeyZc75ISJff_w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_AEnQwVc6EeyZc75ISJff_w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_AEmpsVc6EeyZc75ISJff_w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_AEmpslc6EeyZc75ISJff_w" points="[-22, 17, 37, -448]$[-22, 446, 37, -19]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_AEpF8Fc6EeyZc75ISJff_w" id="(1.0,0.6046511627906976)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_AEpF8Vc6EeyZc75ISJff_w" id="(0.12,0.38)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_TMTTUFc6EeyZc75ISJff_w" type="4001" element="_TMSFMFc6EeyZc75ISJff_w" source="_iluUHExDEeyPd6UCU1TUug" target="_SpEqcFc6EeyZc75ISJff_w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_TMTTU1c6EeyZc75ISJff_w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_TMTTVFc6EeyZc75ISJff_w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_TMTTUVc6EeyZc75ISJff_w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_TMTTUlc6EeyZc75ISJff_w" points="[0, -1, -151, 0]$[150, -1, -1, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_TMVvkFc6EeyZc75ISJff_w" id="(1.0,0.56)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_TMVvkVc6EeyZc75ISJff_w" id="(0.09302325581395349,0.5581395348837209)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_vNDoUFc6EeyZc75ISJff_w" type="4001" element="_vNDBQFc6EeyZc75ISJff_w" source="_SpEqcFc6EeyZc75ISJff_w" target="_exrbAFc6EeyZc75ISJff_w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_vNEPYFc6EeyZc75ISJff_w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_vNEPYVc6EeyZc75ISJff_w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_vNDoUVc6EeyZc75ISJff_w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_vNDoUlc6EeyZc75ISJff_w" points="[0, -7, -398, -19]$[375, -7, -23, -19]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_vNGEkFc6EeyZc75ISJff_w" id="(1.0,0.6511627906976745)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_vNGEkVc6EeyZc75ISJff_w" id="(0.19166666666666668,0.6666666666666666)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_vl60QFc6EeyZc75ISJff_w" type="4001" element="_vl17wFc6EeyZc75ISJff_w" source="_SpEqcFc6EeyZc75ISJff_w" target="_hjnXIFc6EeyZc75ISJff_w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_vl60Q1c6EeyZc75ISJff_w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_vl60RFc6EeyZc75ISJff_w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_vl60QVc6EeyZc75ISJff_w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_vl60Qlc6EeyZc75ISJff_w" points="[-22, 19, -210, -46]$[-22, 65, -210, 0]$[128, 65, -60, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_vl8pcFc6EeyZc75ISJff_w" id="(1.0,0.5581395348837209)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_1NQQMVc6EeyZc75ISJff_w" type="4001" element="_1NPpIFc6EeyZc75ISJff_w" source="_hjnXIFc6EeyZc75ISJff_w" target="_0s4HAFc6EeyZc75ISJff_w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_1NQ3QFc6EeyZc75ISJff_w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_1NQ3QVc6EeyZc75ISJff_w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_1NQQMlc6EeyZc75ISJff_w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_1NQQM1c6EeyZc75ISJff_w" points="[-101, 33, -40, -355]$[-101, 388, -40, 0]$[-82, 388, -21, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_1NSFYFc6EeyZc75ISJff_w" id="(1.0,0.45)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_-DKg8Fc6EeyZc75ISJff_w" type="4001" element="_-DJ54Fc6EeyZc75ISJff_w" source="_0s4HAFc6EeyZc75ISJff_w" target="_gR4NAFc7EeyZc75ISJff_w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_-DKg81c6EeyZc75ISJff_w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_-DKg9Fc6EeyZc75ISJff_w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_-DKg8Vc6EeyZc75ISJff_w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_-DKg8lc6EeyZc75ISJff_w" points="[-22, -32, -228, 39]$[-22, -71, -228, 0]$[185, -71, -21, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_-DMWIFc6EeyZc75ISJff_w" id="(1.0,0.7441860465116279)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_CuWdsFc7EeyZc75ISJff_w" type="4001" element="_CuRlMFc7EeyZc75ISJff_w" source="_0s4HAFc6EeyZc75ISJff_w" target="_AcRGUFc7EeyZc75ISJff_w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_CuXEwFc7EeyZc75ISJff_w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_CuXEwVc7EeyZc75ISJff_w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_CuWdsVc7EeyZc75ISJff_w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_CuWdslc7EeyZc75ISJff_w" points="[0, -6, -338, -12]$[337, -6, -1, -12]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_CuYS4Fc7EeyZc75ISJff_w" id="(1.0,0.627906976744186)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_CuYS4Vc7EeyZc75ISJff_w" id="(0.008333333333333333,0.55)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_GQtKIVc7EeyZc75ISJff_w" type="4001" element="_GQsjEFc7EeyZc75ISJff_w" source="_iuEioFc7EeyZc75ISJff_w" target="_exrbAFc6EeyZc75ISJff_w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_GQtxMFc7EeyZc75ISJff_w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_GQtxMVc7EeyZc75ISJff_w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_GQtKIlc7EeyZc75ISJff_w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_GQtKI1c7EeyZc75ISJff_w" points="[-4, -8, 275, 398]$[-4, -183, 275, 223]$[-291, -183, -12, 223]$[-291, -401, -12, 5]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_GQvmYFc7EeyZc75ISJff_w" id="(0.5813953488372093,0.18604651162790697)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_dxKHQFc8EeyZc75ISJff_w" id="(0.7333333333333333,0.9166666666666666)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_QygU8Fc7EeyZc75ISJff_w" type="4001" element="_Qyft4Fc7EeyZc75ISJff_w" source="__n1OIFc5EeyZc75ISJff_w" target="_QU1hgFc7EeyZc75ISJff_w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_Qyg8AFc7EeyZc75ISJff_w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Qyg8AVc7EeyZc75ISJff_w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_QygU8Vc7EeyZc75ISJff_w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_QygU8lc7EeyZc75ISJff_w" points="[0, -1, -149, 0]$[153, -19, 4, -18]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_QyixMFc7EeyZc75ISJff_w" id="(1.0,0.5)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_byiT4Fc7EeyZc75ISJff_w" type="4001" element="_byhs0Fc7EeyZc75ISJff_w" source="_QU1hgFc7EeyZc75ISJff_w" target="_aHfHUFc7EeyZc75ISJff_w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_byi68Fc7EeyZc75ISJff_w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_byi68Vc7EeyZc75ISJff_w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_byiT4Vc7EeyZc75ISJff_w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_byiT4lc7EeyZc75ISJff_w" points="[-22, -28, -94, 34]$[-22, -63, -94, -1]$[71, -63, -1, -1]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_bykJEFc7EeyZc75ISJff_w" id="(1.0,0.6511627906976745)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_bykJEVc7EeyZc75ISJff_w" id="(0.008333333333333333,0.5166666666666667)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_cQLSIFc7EeyZc75ISJff_w" type="4001" element="_cQHAsFc7EeyZc75ISJff_w" source="_QU1hgFc7EeyZc75ISJff_w" target="_TFlx4Fc7EeyZc75ISJff_w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_cQLSI1c7EeyZc75ISJff_w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_cQL5MFc7EeyZc75ISJff_w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_cQLSIVc7EeyZc75ISJff_w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_cQLSIlc7EeyZc75ISJff_w" points="[0, -5, -349, -6]$[337, -5, -12, -6]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_cQNHUFc7EeyZc75ISJff_w" id="(1.0,0.6046511627906976)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_cQNHUVc7EeyZc75ISJff_w" id="(0.1,0.45)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_eEDqkFc7EeyZc75ISJff_w" type="4001" element="_eECccFc7EeyZc75ISJff_w" source="_aHfHUFc7EeyZc75ISJff_w" target="_0s4HAFc6EeyZc75ISJff_w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_eEDqk1c7EeyZc75ISJff_w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_eEDqlFc7EeyZc75ISJff_w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_eEDqkVc7EeyZc75ISJff_w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_eEDqklc7EeyZc75ISJff_w" points="[-61, -29, 15, 177]$[-61, -181, 15, 25]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_eEFfwFc7EeyZc75ISJff_w" id="(1.0,0.48333333333333334)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_eEFfwVc7EeyZc75ISJff_w" id="(0.13953488372093023,0.4186046511627907)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_gR9FgVc7EeyZc75ISJff_w" type="4001" element="_gR8ecFc7EeyZc75ISJff_w" source="_gR4NAFc7EeyZc75ISJff_w" target="_exrbAFc6EeyZc75ISJff_w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_gR9skFc7EeyZc75ISJff_w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_gR9skVc7EeyZc75ISJff_w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_gR9Fglc7EeyZc75ISJff_w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_gR9Fg1c7EeyZc75ISJff_w" points="[0, -21, -20, 363]$[0, -354, -20, 30]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_h1Co4Fc7EeyZc75ISJff_w" type="4001" element="_h0-XcFc7EeyZc75ISJff_w" source="_gR4NAFc7EeyZc75ISJff_w" target="_TFlx4Fc7EeyZc75ISJff_w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_h1Co41c7EeyZc75ISJff_w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_h1DP8Fc7EeyZc75ISJff_w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_h1Co4Vc7EeyZc75ISJff_w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_h1Co4lc7EeyZc75ISJff_w" points="[-24, 9, -47, -294]$[-24, 289, -47, -14]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_h1EeEFc7EeyZc75ISJff_w" id="(1.0,0.7209302325581395)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_h1EeEVc7EeyZc75ISJff_w" id="(0.55,0.23333333333333334)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_jDpxElc7EeyZc75ISJff_w" type="4001" element="_jDpKAFc7EeyZc75ISJff_w" source="_AcRGUFc7EeyZc75ISJff_w" target="_iuEioFc7EeyZc75ISJff_w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_jDqYIFc7EeyZc75ISJff_w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_jDqYIVc7EeyZc75ISJff_w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_jDpxE1c7EeyZc75ISJff_w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_jDpxFFc7EeyZc75ISJff_w" points="[0, 2, -93, 4]$[89, 2, -4, 4]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_jDrmQFc7EeyZc75ISJff_w" id="(1.0,0.45)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_jDrmQVc7EeyZc75ISJff_w" id="(0.09302325581395349,0.3953488372093023)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_lRHHIFc7EeyZc75ISJff_w" type="4001" element="_lRCOoFc7EeyZc75ISJff_w" source="_iuEioFc7EeyZc75ISJff_w" target="_TFlx4Fc7EeyZc75ISJff_w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_lRHHI1c7EeyZc75ISJff_w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_lRHHJFc7EeyZc75ISJff_w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_lRHHIVc7EeyZc75ISJff_w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_lRHHIlc7EeyZc75ISJff_w" points="[-22, 17, 284, -247]$[-22, 101, 284, -163]$[-290, 101, 16, -163]$[-290, 234, 16, -30]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_lRI8UFc7EeyZc75ISJff_w" id="(1.0,0.6046511627906976)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_6tg-UFc7EeyZc75ISJff_w" type="4001" element="_6tgXQFc7EeyZc75ISJff_w" source="_TFlx4Fc7EeyZc75ISJff_w" target="_6JAjEFc7EeyZc75ISJff_w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_6tg-U1c7EeyZc75ISJff_w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_6thlYFc7EeyZc75ISJff_w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_6tg-UVc7EeyZc75ISJff_w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_6tg-Ulc7EeyZc75ISJff_w" points="[0, 7, -130, 5]$[131, 23, 1, 21]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_6tizgFc7EeyZc75ISJff_w" id="(1.0,0.45)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_7KIB0Fc7EeyZc75ISJff_w" type="4001" element="_7KGzsFc7EeyZc75ISJff_w" source="_6JAjEFc7EeyZc75ISJff_w" target="_aHfHUFc7EeyZc75ISJff_w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_7KIB01c7EeyZc75ISJff_w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_7KIB1Fc7EeyZc75ISJff_w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_7KIB0Vc7EeyZc75ISJff_w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_7KIB0lc7EeyZc75ISJff_w" points="[-22, 14, 472, 93]$[-22, 54, 472, 133]$[-495, 54, -1, 133]$[-495, -49, -1, 30]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_7KJ3AFc7EeyZc75ISJff_w" id="(1.0,0.6744186046511628)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_DqgHcFc8EeyZc75ISJff_w" type="4001" element="_DqbO8Fc8EeyZc75ISJff_w" source="_6JAjEFc7EeyZc75ISJff_w" target="_Cytj0Fc8EeyZc75ISJff_w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_DqgHc1c8EeyZc75ISJff_w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_DqgHdFc8EeyZc75ISJff_w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_DqgHcVc8EeyZc75ISJff_w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_DqgHclc8EeyZc75ISJff_w" points="[0, -5, -351, 489]$[339, -5, -12, 489]$[339, -469, -12, 25]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_DqhVkFc8EeyZc75ISJff_w" id="(1.0,0.6046511627906976)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Y8EAkFc8EeyZc75ISJff_w" type="4001" element="_Y7958Fc8EeyZc75ISJff_w" source="_6JAjEFc7EeyZc75ISJff_w" target="_UzDj0Fc8EeyZc75ISJff_w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_Y8EAk1c8EeyZc75ISJff_w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Y8EAlFc8EeyZc75ISJff_w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Y8EAkVc8EeyZc75ISJff_w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Y8EAklc8EeyZc75ISJff_w" points="[-22, -29, -148, 29]$[-22, -59, -148, -1]$[111, -59, -15, -1]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_Y8F1wFc8EeyZc75ISJff_w" id="(1.0,0.6744186046511628)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_exhYElc8EeyZc75ISJff_w" type="4001" element="_exgxAFc8EeyZc75ISJff_w" source="_exrbAFc6EeyZc75ISJff_w" target="_bXv_4Fc8EeyZc75ISJff_w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_exh_IFc8EeyZc75ISJff_w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_exh_IVc8EeyZc75ISJff_w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_exhYE1c8EeyZc75ISJff_w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_exhYFFc8EeyZc75ISJff_w" points="[0, 0, -115, 6]$[108, 0, -7, 6]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_exjNQFc8EeyZc75ISJff_w" id="(1.0,0.48333333333333334)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_exjNQVc8EeyZc75ISJff_w" id="(0.16279069767441862,0.3488372093023256)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_iB_DQFc8EeyZc75ISJff_w" type="4001" element="_iB-cMFc8EeyZc75ISJff_w" source="_bXv_4Fc8EeyZc75ISJff_w" target="_hjnXIFc6EeyZc75ISJff_w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_iB_DQ1c8EeyZc75ISJff_w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_iB_DRFc8EeyZc75ISJff_w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_iB_DQVc8EeyZc75ISJff_w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_iB_DQlc8EeyZc75ISJff_w" points="[-22, -29, 452, -64]$[-22, -82, 452, -117]$[-459, -82, 15, -117]$[-459, 22, 15, -13]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_iCA4cFc8EeyZc75ISJff_w" id="(1.0,0.6744186046511628)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_iCA4cVc8EeyZc75ISJff_w" id="(0.36666666666666664,0.21666666666666667)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_jQFOEFc8EeyZc75ISJff_w" type="4001" element="_jQCKwFc8EeyZc75ISJff_w" source="_bXv_4Fc8EeyZc75ISJff_w" target="_Cytj0Fc8EeyZc75ISJff_w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_jQFOE1c8EeyZc75ISJff_w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_jQFOFFc8EeyZc75ISJff_w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_jQFOEVc8EeyZc75ISJff_w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_jQFOElc8EeyZc75ISJff_w" points="[0, -6, -238, -216]$[239, -6, 1, -216]$[239, 204, 1, -6]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_jQGcMFc8EeyZc75ISJff_w" id="(1.0,0.627906976744186)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_jQGcMVc8EeyZc75ISJff_w" id="(0.53,0.12)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_nPwvsFc8EeyZc75ISJff_w" type="4001" element="_nPqpEFc8EeyZc75ISJff_w" source="_bXv_4Fc8EeyZc75ISJff_w" target="_k0RksFc8EeyZc75ISJff_w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_nPwvs1c8EeyZc75ISJff_w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_nPwvtFc8EeyZc75ISJff_w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_nPwvsVc8EeyZc75ISJff_w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_nPwvslc8EeyZc75ISJff_w" points="[-30, 6, 39, -64]$[-73, 68, -4, -2]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_nPx90Fc8EeyZc75ISJff_w" id="(1.0,0.6511627906976745)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_nPx90Vc8EeyZc75ISJff_w" id="(0.16666666666666666,0.3333333333333333)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_u16BsFc8EeyZc75ISJff_w" type="4001" element="_u15aoFc8EeyZc75ISJff_w" source="_Cytj0Fc8EeyZc75ISJff_w" target="_tHuooFc8EeyZc75ISJff_w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_u16Bs1c8EeyZc75ISJff_w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_u16BtFc8EeyZc75ISJff_w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_u16BsVc8EeyZc75ISJff_w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_u16Bslc8EeyZc75ISJff_w" points="[0, -3, -154, 0]$[148, -3, -6, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_u17P0Fc8EeyZc75ISJff_w" id="(1.0,0.56)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_u17P0Vc8EeyZc75ISJff_w" id="(0.16279069767441862,0.5116279069767442)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_zIEacVc8EeyZc75ISJff_w" type="4001" element="_zIDzYFc8EeyZc75ISJff_w" source="_tHuooFc8EeyZc75ISJff_w" target="_9yTP4Fc5EeyZc75ISJff_w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_zIFBgFc8EeyZc75ISJff_w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_zIFBgVc8EeyZc75ISJff_w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_zIEaclc8EeyZc75ISJff_w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_zIEac1c8EeyZc75ISJff_w" points="[-22, -26, 1214, -16]$[-22, -74, 1214, -64]$[-1107, -74, 129, -64]$[-1107, -9, 129, 1]$[-1215, -9, 21, 1]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_zIGPoFc8EeyZc75ISJff_w" id="(1.0,0.6046511627906976)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_4b8u4Fc8EeyZc75ISJff_w" type="4001" element="_4b4dcFc8EeyZc75ISJff_w" source="_tHuooFc8EeyZc75ISJff_w" target="_35s9cFc8EeyZc75ISJff_w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_4b8u41c8EeyZc75ISJff_w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_4b8u5Fc8EeyZc75ISJff_w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_4b8u4Vc8EeyZc75ISJff_w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_4b8u4lc8EeyZc75ISJff_w" points="[0, -8, -143, 0]$[128, -8, -15, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_4b99AFc8EeyZc75ISJff_w" id="(1.0,0.6744186046511628)"/>
    </edges>
  </notation:Diagram>
</xmi:XMI>
